# Aula 02 - Python
Atividade 01 - Praticando com Python\
Desenvolvedor: Ana Julia Pietroski Anderson\
Matrícula: 20206355


## Dados numéricos


In [8]:
# Variável inteira
a = 1
print('Valor de a = '+str(a))
type(a)

Valor de a = 1


int

In [9]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)

1.0


float

In [10]:
# Converter float para int
c = int(b)
print(c)
type(c)

1


int

In [11]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [12]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


## Dados de texto

In [13]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


## Dados tipo bool - lógica

In [14]:
a == 1

True

In [15]:
h = (a==1)
print(h)
type(h)

True


bool

In [17]:
h = (a==2)
print(h)
type(h)

False


bool

In [18]:
i = True
type(i)

bool

In [19]:
ii = 'True'
type(ii)

str

### Operação de comparação

In [20]:
# Operação ==
a==b

True

In [21]:
# Operação ><
a>b

False

In [22]:
# Operação !=
a!=b

False

In [23]:
# Operação >= ou <=
a>=b

True

## Operações matemáticas

In [24]:
# Soma
a+b

2.0

In [25]:
# Soma e atribui valor
ab = a+b
print(ab)

2.0


In [26]:
# Multiplicação 
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [27]:
# Divisão
a/b

1.0

In [28]:
# Potencia
5**2

25

In [29]:
# Operações matemáticas com a biblioteca math
import math

math.exp(10)

22026.465794806718

In [31]:
math.exp(0)

1.0

In [32]:
math.exp(a)

2.718281828459045

In [33]:
math.exp(-10)

4.5399929762484854e-05

In [34]:
import math as mt 
mt.log(c)

0.0

In [35]:
mt.log10(100)

2.0

## Listas

In [36]:
myFirstList = [1,2,3,]
print(myFirstList)

[1, 2, 3]


In [37]:
# Acessando valores da lista pelo index
print(myFirstList[0])
print(myFirstList[2])

1
3


In [38]:
myFirstList==a

False

In [39]:
myFirstList[0]==a

True

In [40]:
mySecList = [1,a,'c']
print(mySecList)

[1, 1, 'c']


In [42]:
type(mySecList)

list

In [43]:
type(mySecList[2])

str

In [44]:
type(mySecList[1])

int

## Caminhos = path

In [45]:
path = r"C:\Users\anaju\OneDrive\Documentos\GitHub\Controle_AnaPietroski"
print(path)

C:\Users\anaju\OneDrive\Documentos\GitHub\Controle_AnaPietroski


In [52]:
path = "C:/Users/anaju/OneDrive/Documentos/GitHub/Controle_AnaPietroski"
print(path)

C:/Users/anaju/OneDrive/Documentos/GitHub/Controle_AnaPietroski


In [56]:
import os
# Listar arquivos na pasta
os.listdir(path)

['.git',
 '.gitignore',
 'Aula01.ipynb',
 'inputs',
 'README.md',
 'scripts',
 'venv']

In [57]:
# Selecionar priemrio arquivo listado
os.listdir(path)[0]

'.git'

In [58]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:/Users/anaju/OneDrive/Documentos/GitHub/Controle_AnaPietroski/.git'

In [60]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [62]:
# Diretório que estou trabalhando 
os.getcwd()

'C:\\Users\\anaju\\OneDrive\\Documentos\\GitHub\\Controle_AnaPietroski\\venv\\Scripts'

In [63]:
# Mudo de diretório para o caminho
os.chdir('C:\\Users\\anaju\\OneDrive\\Documentos\\')

In [64]:
os.getcwd()

'C:\\Users\\anaju\\OneDrive\\Documentos'

In [84]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

diretório já existe


In [85]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

diretório já existe


## Numpy arrays e Pandas DataFrames

In [94]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [95]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [96]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)

[[0.60117001 0.00822593 0.15481015 0.45345113 0.56169144 0.45716461
  0.70049239 0.31826142 0.29013159 0.35672758]
 [0.47258855 0.63046966 0.71900715 0.53807021 0.72167706 0.76143002
  0.5367401  0.51785293 0.03557509 0.55384281]
 [0.54245898 0.33895379 0.92236747 0.5957384  0.35668771 0.96890089
  0.7646705  0.65832751 0.41185916 0.68530276]
 [0.3470595  0.46011423 0.63717225 0.21128312 0.16933229 0.54016402
  0.29957946 0.288187   0.41570548 0.42231308]
 [0.21364271 0.67474312 0.09903974 0.4312101  0.29343744 0.60846586
  0.21427523 0.90953321 0.2314893  0.91975851]
 [0.16549543 0.17319276 0.93591248 0.17805495 0.87159369 0.83385128
  0.85456428 0.32146281 0.14219794 0.65971615]
 [0.57419835 0.31352187 0.29345056 0.34420437 0.4903171  0.37022673
  0.23839041 0.44475604 0.22597467 0.76507504]
 [0.41164288 0.41397492 0.30075102 0.74772832 0.22045522 0.39261884
  0.87835506 0.16554566 0.08041258 0.90350276]
 [0.55768505 0.09728268 0.47180163 0.0355238  0.22287061 0.51205061
  0.59495744

In [97]:
# Acessando valores da matriz
n[0,:]

array([0.60117001, 0.00822593, 0.15481015, 0.45345113, 0.56169144,
       0.45716461, 0.70049239, 0.31826142, 0.29013159, 0.35672758])

In [98]:
n[:,0]

array([0.60117001, 0.47258855, 0.54245898, 0.3470595 , 0.21364271,
       0.16549543, 0.57419835, 0.41164288, 0.55768505, 0.30933497])

In [99]:
n[:,1:5]

array([[0.00822593, 0.15481015, 0.45345113, 0.56169144],
       [0.63046966, 0.71900715, 0.53807021, 0.72167706],
       [0.33895379, 0.92236747, 0.5957384 , 0.35668771],
       [0.46011423, 0.63717225, 0.21128312, 0.16933229],
       [0.67474312, 0.09903974, 0.4312101 , 0.29343744],
       [0.17319276, 0.93591248, 0.17805495, 0.87159369],
       [0.31352187, 0.29345056, 0.34420437, 0.4903171 ],
       [0.41397492, 0.30075102, 0.74772832, 0.22045522],
       [0.09728268, 0.47180163, 0.0355238 , 0.22287061],
       [0.63455069, 0.94911069, 0.00393501, 0.81756174]])

In [100]:
n[0,1:5]

array([0.00822593, 0.15481015, 0.45345113, 0.56169144])

In [101]:
n[0,-1]

0.3567275751643686

In [102]:
n[0,4:-1]

array([0.56169144, 0.45716461, 0.70049239, 0.31826142, 0.29013159])

In [103]:
n[0,4:]

array([0.56169144, 0.45716461, 0.70049239, 0.31826142, 0.29013159,
       0.35672758])

In [104]:
an = np.log(n*5)
print(an)

[[ 1.10056041 -3.19102593 -0.25611784  0.81857013  1.03263529  0.82672615
   1.25346613  0.46455575  0.37201722  0.57865503]
 [ 0.85990776  1.14814766  1.27955394  0.98967168  1.28326039  1.33688091
   0.98719662  0.95137392 -1.72667179  1.01856355]
 [ 0.99779511  0.52754642  1.52862634  1.09148427  0.57854327  1.57784496
   1.34112766  1.19138518  0.72236407  1.23154336]
 [ 0.55117886  0.83315743  1.15872266  0.05488165 -0.16645434  0.99355546
   0.40406234  0.36529222  0.73165966  0.74742957]
 [ 0.06598767  1.2160147  -0.70279614  0.76827809  0.3833471   1.11262343
   0.06894394  1.51461414  0.1462163   1.52579378]
 [-0.18937381 -0.14391215  1.5432046  -0.11622518  1.47200599  1.42773769
   1.45227436  0.47456448 -0.34109734  1.19349231]
 [ 1.05465753  0.44955175  0.3833918   0.54291821  0.89673496  0.61579825
   0.17559234  0.79920854  0.12210557  1.34165655]
 [ 0.72183882  0.72748803  0.40796537  1.31872234  0.09737723  0.67452189
   1.47973355 -0.18907032 -0.91114673  1.5079618 ]
